//! Ticket encoding / decoding.
//!
//! Wire format (spec §03):
//!
//! ```text
//! msgpack_payload = msgpack(fields)
//! wire            = blake3(msgpack_payload)[:4] || msgpack_payload
//! ticket          = base64url_nopad(wire)
//! ```

use std::collections::HashMap;

use data_encoding::BASE64URL_NOPAD;
use rmpv::Value;
use serde::{Deserialize, Serialize};

use crate::{error::LerpError, identity::EndpointId};

/// Current lerp protocol version string.
pub const LERP_VERSION: &str = "0.1.0-dev";

/// Number of bytes used as a checksum prefix in the wire format.
pub const CHECKSUM_LEN: usize = 4;

// ---------------------------------------------------------------------------
// Custom serde helper: Option<[u8; 32]> ↔ msgpack bin
//
// serde_bytes works on &[u8] / Vec<u8> / ByteBuf but not on [u8; N] inside
// an Option.  This tiny module bridges the gap so Ticket can be derived
// directly without an intermediate TicketWire struct.
// ---------------------------------------------------------------------------

mod opt_bytes32 {
    use serde::{de::Error as _, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(v: &Option<[u8; 32]>, s: S) -> Result<S::Ok, S::Error> {
        match v {
            Some(b) => s.serialize_bytes(b),
            None => s.serialize_none(),
        }
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Option<[u8; 32]>, D::Error> {
        let opt: Option<serde_bytes::ByteBuf> = serde::Deserialize::deserialize(d)?;
        match opt {
            None => Ok(None),
            Some(buf) => {
                let arr: [u8; 32] = buf
                    .into_vec()
                    .try_into()
                    .map_err(|_| D::Error::custom("lerp_sec must be exactly 32 bytes"))?;
                Ok(Some(arr))
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Public Ticket
// ---------------------------------------------------------------------------

/// A lerp capability ticket.
///
/// Holds all information needed to connect to a target endpoint and optional
/// application-level metadata. Serialize to a shareable string with
/// [`Ticket::encode`]; parse back with [`Ticket::decode`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ticket {
    /// `lerp_ver`: lerp protocol version string.
    pub lerp_ver: String,

    /// `lerp_eid`: target endpoint's identity, base32-encoded Ed25519 public key.
    pub lerp_eid: String,

    /// `lerp_rly`: optional relay server hostname (e.g. `"relay.example.com"`).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub lerp_rly: Option<String>,

    /// `lerp_sec`: optional 32-byte relay secret.
    /// Must be `Some` iff `lerp_rly` is `Some`.
    #[serde(with = "opt_bytes32", skip_serializing_if = "Option::is_none", default)]
    pub lerp_sec: Option<[u8; 32]>,

    /// `lerp_dir`: optional list of direct-connect candidate addresses.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub lerp_dir: Option<Vec<String>>,

    /// Application-defined key-value pairs (any key not starting with `lerp_`).
    #[serde(flatten)]
    pub app_fields: HashMap<String, Value>,
}

impl Ticket {
    // -----------------------------------------------------------------------
    // Constructors / builders
    // -----------------------------------------------------------------------

    /// Create a minimal ticket for `endpoint_id` (no relay, no direct addrs).
    pub fn new(endpoint_id: &EndpointId) -> Self {
        Self {
            lerp_ver: LERP_VERSION.to_string(),
            lerp_eid: endpoint_id.to_base32(),
            lerp_rly: None,
            lerp_sec: None,
            lerp_dir: None,
            app_fields: HashMap::new(),
        }
    }

    /// Attach relay information.
    ///
    /// `relay_host` is the bare hostname; `relay_secret` is 32 random bytes
    /// generated by the ticket creator.
    pub fn with_relay(mut self, relay_host: String, relay_secret: [u8; 32]) -> Self {
        self.lerp_rly = Some(relay_host);
        self.lerp_sec = Some(relay_secret);
        self
    }

    /// Attach direct-connect candidate addresses.
    pub fn with_direct(mut self, addrs: Vec<String>) -> Self {
        self.lerp_dir = Some(addrs);
        self
    }

    /// Insert an arbitrary application field.
    pub fn with_app_field(mut self, key: impl Into<String>, value: Value) -> Self {
        self.app_fields.insert(key.into(), value);
        self
    }

    // -----------------------------------------------------------------------
    // Accessors
    // -----------------------------------------------------------------------

    /// Parse and return the endpoint id.
    pub fn endpoint_id(&self) -> Result<EndpointId, LerpError> {
        EndpointId::from_base32(&self.lerp_eid)
    }

    /// Return the relay secret bytes if present.
    pub fn relay_secret(&self) -> Option<&[u8; 32]> {
        self.lerp_sec.as_ref()
    }

    /// Return `true` if this ticket carries both a relay URL and a relay secret.
    pub fn has_relay(&self) -> bool {
        self.lerp_rly.is_some() && self.lerp_sec.is_some()
    }

    // -----------------------------------------------------------------------
    // Encoding
    // -----------------------------------------------------------------------

    /// Encode the ticket to a base64url (no padding) string.
    pub fn encode(&self) -> Result<String, LerpError> {
        let payload = self.to_msgpack()?;
        let binding = blake3::hash(&payload);
        let checksum = &binding.as_bytes()[..CHECKSUM_LEN];

        let mut wire = Vec::with_capacity(CHECKSUM_LEN + payload.len());
        wire.extend_from_slice(checksum);
        wire.extend_from_slice(&payload);

        Ok(BASE64URL_NOPAD.encode(&wire))
    }

    /// Decode and validate a ticket string produced by [`Ticket::encode`].
    pub fn decode(s: &str) -> Result<Self, LerpError> {
        // 1. base64url decode
        let wire = BASE64URL_NOPAD
            .decode(s.as_bytes())
            .map_err(|e| LerpError::InvalidTicket(format!("base64url: {e}")))?;

        if wire.len() < CHECKSUM_LEN {
            return Err(LerpError::InvalidTicket("wire too short".into()));
        }

        // 2. BLAKE3 checksum
        let (checksum, payload) = wire.split_at(CHECKSUM_LEN);
        let binding = blake3::hash(payload);
        let expected = &binding.as_bytes()[..CHECKSUM_LEN];
        if checksum != expected {
            return Err(LerpError::InvalidTicket(
                "checksum mismatch - ticket corrupted".into(),
            ));
        }

        // 3. msgpack → Ticket
        let ticket = Self::from_msgpack(payload)?;

        // 4. version check (warn, don't reject — allows forward compatibility)
        if ticket.lerp_ver != LERP_VERSION {
            tracing::warn!(
                remote_ver = %ticket.lerp_ver,
                "ticket version differs from local"
            );
        }

        // 5. validate endpoint_id is a well-formed Ed25519 public key
        ticket.endpoint_id()?;

        // 6. relay fields must both be present or both absent
        if ticket.lerp_rly.is_some() != ticket.lerp_sec.is_some() {
            return Err(LerpError::InvalidTicket(
                "lerp_rly and lerp_sec must both be present or both absent".into(),
            ));
        }

        Ok(ticket)
    }

    // -----------------------------------------------------------------------
    // Private msgpack helpers
    // -----------------------------------------------------------------------

    fn to_msgpack(&self) -> Result<Vec<u8>, LerpError> {
        rmp_serde::to_vec_named(self)
            .map_err(|e| LerpError::Serialization(e.to_string()))
    }

    fn from_msgpack(data: &[u8]) -> Result<Self, LerpError> {
        rmp_serde::from_slice(data)
            .map_err(|e| LerpError::Serialization(e.to_string()))
    }
}
